# Generated by Django 5.1.4 on 2025-01-16 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0015_alter_product_productstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OrderStatus', models.CharField(choices=[('Pending', 'Pending'), ('Sold', 'Sold')], default='Pending', max_length=10)),
                ('ShippingAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('OrderType', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite')], default='Onsite', max_length=10)),
                ('Discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('CashierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sale.order')),
            ],
        ),
    ]
