# Generated by Django 5.1.4 on 2025-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('PasswordHash', models.CharField(max_length=200)),
                ('HireDate', models.DateTimeField(auto_now_add=True)),
                ('Role', models.CharField(max_length=100)),
                ('AdminRoleConfiguration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProductDescription', models.TextField()),
                ('ProductQuantity', models.PositiveIntegerField()),
                ('ProductType', models.CharField(max_length=100)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductBarcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField(max_length=255)),
                ('Description', models.TextField(max_length=255)),
            ],
        ),
    ]
