# Generated by Django 5.1.6 on 2025-02-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_type', models.CharField(max_length=100)),
                ('product_status', models.BooleanField(default=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_barcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('suppliers', models.ManyToManyField(blank=True, to='Inventory.supplier')),
            ],
        ),
    ]
