# Generated by Django 5.1.6 on 2025-02-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Bread/Bakery', 'Bread/Bakery'), ('Canned Goods', 'Canned Goods'), ('Dairy', 'Dairy'), ('Dry Goods', 'Dry Goods'), ('Meat', 'Meat'), ('Produce', 'Produce'), ('Snacks', 'Snacks'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
