# Generated by Django 5.1.4 on 2025-01-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BarcodeImage',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductBarcode',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
