# Generated by Django 5.1.4 on 2025-01-10 09:08

import django.core.files.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_barcodeimage_alter_product_productbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BarcodeImage',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='media/barcodes'), upload_to='barcodes/'),
            preserve_default=False,
        ),
    ]
