# Generated by Django 5.1.6 on 2025-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_product_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Pork', 'Pork'), ('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Seafood', 'Seafood'), ('Ready To Cook', 'Ready To Cook'), ('Eggs', 'Eggs'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
