# Generated by Django 5.1.4 on 2025-01-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=models.ManyToManyField(blank=True, to='Inventory.supplier'),
        ),
    ]
