# Generated by Django 5.1.4 on 2025-01-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_remove_product_supplier_product_suppliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProjectName',
            new_name='ProductName',
        ),
    ]
