# Generated by Django 5.1.6 on 2025-02-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_inventorytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='manager',
        ),
    ]
