# Generated by Django 5.1.4 on 2025-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_rename_projectname_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BarcodeImage',
            field=models.ImageField(blank=True, storage=models.ImageField(blank=True, upload_to='barcodes/'), upload_to='barcodes/'),
        ),
    ]
