# Generated by Django 5.1.4 on 2025-01-11 13:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_product_barcodeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='BarcodeImage',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/barcodes'), upload_to='barcodes/'),
        ),
    ]
