# Generated by Django 5.1.6 on 2025-02-27 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_alter_inventorytransaction_user'),
        ('accounts', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='accounts.userprofile'),
        ),
    ]
