# Generated by Django 5.1.4 on 2025-01-11 17:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_alter_product_barcodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BarcodeImage',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\Frap\\APC-2024-2025-T1-05-3-L-Variety-Store\\InventoryManagementSystem\\VarietyStore\\media'), upload_to='barcodes/'),
        ),
    ]
