# Generated by Django 5.1.4 on 2025-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_alter_product_barcodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BarcodeImage',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
