# Generated by Django 5.1.6 on 2025-03-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_weeklyreport_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='total_profit_or_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
