# Generated by Django 5.1.6 on 2025-03-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_weeklyreport_total_profit_or_loss'),
        ('accounts', '0004_alter_userprofile_user_alter_role_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'get_latest_by': 'start_date', 'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='cost_at_transaction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='price_at_transaction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
