# Generated by Django 5.1.4 on 2025-01-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_alter_product_barcodeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
