# Generated by Django 5.1.4 on 2025-01-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductStatus',
            field=models.BooleanField(default=True),
        ),
    ]
