# Generated by Django 5.1.4 on 2025-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_product_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductStatus',
            field=models.BooleanField(default=False),
        ),
    ]
